// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKm-RJBv-BVviRpH4jvwhoRKNRfLwmmvQ',
    appId: '1:682107704587:web:771f287d27968e4e943e0e',
    messagingSenderId: '682107704587',
    projectId: 'patitasacasa-7882d',
    authDomain: 'patitasacasa-7882d.firebaseapp.com',
    storageBucket: 'patitasacasa-7882d.appspot.com',
    measurementId: 'G-GSWN23Y8R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByBqx46BhKvOHHgkWhK0HZYTrgZ5fPwao',
    appId: '1:682107704587:android:c63680da9b714976943e0e',
    messagingSenderId: '682107704587',
    projectId: 'patitasacasa-7882d',
    storageBucket: 'patitasacasa-7882d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzdBjCx1_rf6xm4CzH7xd2B6XGSjJBSu8',
    appId: '1:682107704587:ios:6a54a228cd31b4fa943e0e',
    messagingSenderId: '682107704587',
    projectId: 'patitasacasa-7882d',
    storageBucket: 'patitasacasa-7882d.appspot.com',
    iosClientId: '682107704587-ne0ja238n654gv0hi3im4l9k7bbu60o3.apps.googleusercontent.com',
    iosBundleId: 'com.patitas.A.casa',
  );
}
